name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Deploy to GitHub Pages
        run: echo "🚀 Deploying..."
